import dotenv from 'dotenv';
import mongoose from 'mongoose';
import {Doctor} from '../models/doctorModel.js';

dotenv.config({
    path:"./.env"
})


export const doctors = [
    {
      SNo: 1,
      FullName: "Dr. Uday Chandra Chaudhary",
      Degree: "MD",
      Speciality: "ORTHOPAEDICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nobel Medical College",
      FNDRegistrationNo: "019-99-005177-13",
      RegistrationValidity: "2021-03-11",
    },
    {
      SNo: 2,
      FullName: "Dr. Maarit Lrene Valkealahti",
      Degree: "MD",
      Speciality: "ORTHOPAEDIC",
      Nationality: "Finland",
      Gender: "Female",
      WorkingPlace: "United Mission To Nepal Medical and Development Trust",
      FNDRegistrationNo: "005-72-006313-19",
      RegistrationValidity: "2023-06-16",
    },
    {
      SNo: 3,
      FullName: "Dr. Kailash Chandra",
      Degree: "MS",
      Speciality: "GENERAL SURGERY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Universal College of Medical Science",
      FNDRegistrationNo: "023-99-003877-16",
      RegistrationValidity: "28/11/2021",
    },
    {
      SNo: 4,
      FullName: "Dr. Kala Satyavati",
      Degree: "MD",
      Speciality: "PHYSIOLOGY",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006439-20",
      RegistrationValidity: "2025-08-12",
    },
    {
      SNo: 5,
      FullName: "Dr. Vaalisemmagari Venugopal Reddy",
      Degree: "MD",
      Speciality: "SOCIAL & PREVENTIVE MEDICINE",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006440-20",
      RegistrationValidity: "2025-07-01",
    },
    {
      SNo: 6,
      FullName: "Dr. Surendra Kumar",
      Degree: "MD",
      Speciality: "COMMUNITY MEDICINE",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nobel Medical College",
      FNDRegistrationNo: "019-99-004665-18",
      RegistrationValidity: "08/12/2021",
    },
    {
      SNo: 7,
      FullName: "Dr. Akansh Datta",
      Degree: "MD",
      Speciality: "ORAL AND MAXILLOFACIAL SURGERY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "M. B. Kedia Dental College",
      FNDRegistrationNo: "012-99-006444-20",
      RegistrationValidity: "12/12/2021",
    },
    {
      SNo: 8,
      FullName: "Dr. Thomas James Jurich",
      Degree: "MD",
      Speciality: "MD",
      Nationality: "USA",
      Gender: "Male",
      WorkingPlace: "United Mission To Nepal Medical and Development Trust",
      FNDRegistrationNo: "005-223-006516-21",
      RegistrationValidity: "2024-12-21",
    },
    {
      SNo: 9,
      FullName: "Dr.Nutan Bala Singh",
      Degree: "MS",
      Speciality: "OBST & GYNAE",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-006447-20",
      RegistrationValidity: "26/12/2021",
    },
    {
      SNo: 10,
      FullName: "Dr. Rameshwar Prasad",
      Degree: "MD",
      Speciality: "PAEDIATRICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-005173-20",
      RegistrationValidity: "26/12/2021",
    },
    {
      SNo: 11,
      FullName: "Dr. Vasanti Uddhav Arole",
      Degree: "MS",
      Speciality: "ANATOMY",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006041-17",
      RegistrationValidity: "30/12/2021",
    },
    {
      SNo: 12,
      FullName: "Dr.Krishna Kumar",
      Degree: "MD",
      Speciality: "RADIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Birat Medical College",
      FNDRegistrationNo: "025-99-006101-18",
      RegistrationValidity: "31/12/2021",
    },
    {
      SNo: 13,
      FullName: "Dr. Sujit Bhattacharjee",
      Degree: "MD",
      Speciality: "MICROBIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nobel Medical College",
      FNDRegistrationNo: "019-99-006244-18",
      RegistrationValidity: "01/01/2022",
    },
    {
      SNo: 14,
      FullName: "Dr. Md. Zafar Alam",
      Degree: "MD",
      Speciality: "ORTHOPAEDICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nobel Medical College",
      FNDRegistrationNo: "019-99-005171-13",
      RegistrationValidity: "03/01/2022",
    },
    {
      SNo: 15,
      FullName: "Dr. Asok Chakrabarti",
      Degree: "MD",
      Speciality: "ANAESTHESIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Manipal College of Medical Science",
      FNDRegistrationNo: "013-99-006408-20",
      RegistrationValidity: "04/01/2022",
    },
    {
      SNo: 16,
      FullName: "Dr.Thounaojam Darendra Singh",
      Degree: "MD",
      Speciality: "OBSTETRICS AND GYNAECOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nobel Medical College",
      FNDRegistrationNo: "019-99-006256-19",
      RegistrationValidity: "05/01/2022",
    },
    {
      SNo: 17,
      FullName: "Dr. Swapan Kumar Roy",
      Degree: "MD",
      Speciality: "MICROBIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Birat Medical College",
      FNDRegistrationNo: "025-99-005837-17",
      RegistrationValidity: "07/01/2022",
    },
    {
      SNo: 18,
      FullName: "Dr. Sharad Digamdar Bhat",
      Degree: "MS",
      Speciality: "MICROBIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nepalgunj Medical College",
      FNDRegistrationNo: "017-99-005836-17",
      RegistrationValidity: "07/01/2022",
    },
    {
      SNo: 19,
      FullName: "Dr. Omprakash Agrawal",
      Degree: "MD",
      Speciality: "SPM",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006061-18",
      RegistrationValidity: "10/01/2022",
    },
    {
      SNo: 20,
      FullName: "Dr.Vilas Babu Sangappa Korwar",
      Degree: "MD",
      Speciality: "ORTHOPAEDICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Lumbini Medical College",
      FNDRegistrationNo: "011-99-006318-19",
      RegistrationValidity: "30/01/2022",
    },
    {
      SNo: 21,
      FullName: "Dr. Dilip Kumar",
      Degree: "MD",
      Speciality: "RADIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Birat Medical College",
      FNDRegistrationNo: "025-99-006466-21",
      RegistrationValidity: "06/02/2022",
    },
    {
      SNo: 22,
      FullName: "Dr.Gajendra Choudhary",
      Degree: "MD",
      Speciality: "ANESTHESIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-006467-21",
      RegistrationValidity: "13/02/2022",
    },
    {
      SNo: 23,
      FullName: "Dr.Shambhu Nath Singh",
      Degree: "MD",
      Speciality: "PHARMACOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-006468-21",
      RegistrationValidity: "13/02/2022",
    },
    {
      SNo: 24,
      FullName: "Dr.Yaswant Kumar Singh",
      Degree: "MD",
      Speciality: "MICROBIOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-006469-21",
      RegistrationValidity: "13/02/2022",
    },
    {
      SNo: 25,
      FullName: "Dr. Arnab Ghosh",
      Degree: "MD",
      Speciality: "PATHOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Manipal College of Medical Science",
      FNDRegistrationNo: "013-99-002065-03",
      RegistrationValidity: "14/02/2022",
    },
    {
      SNo: 26,
      FullName: "Dr. Ningombam Jitendra Singh",
      Degree: "MD",
      Speciality: "OBSTETRICS AND GYNAECOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nobel Medical College",
      FNDRegistrationNo: "019-99-006418-20",
      RegistrationValidity: "22/02/2022",
    },
    {
      SNo: 27,
      FullName: "Dr. Jaideep Chandra",
      Degree: "MS",
      Speciality: "GENERAL SURGERY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Universal College of Medical Science",
      FNDRegistrationNo: "023-99-005433-14",
      RegistrationValidity: "22/02/2022",
    },
    {
      SNo: 28,
      FullName: "Dr.Tarun Kumar Gaur",
      Degree: "MDS",
      Speciality: "OPERATIVE DENTISTRY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "People's Dental College",
      FNDRegistrationNo: "021-99-006275-19",
      RegistrationValidity: "23/02/2022",
    },
    {
      SNo: 29,
      FullName: "Dr. Sharad Hemant",
      Degree: "MS",
      Speciality: "OPHTHALMOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nepal Netra Jyoti Sangh.",
      FNDRegistrationNo: "014-99-006497-21",
      RegistrationValidity: "24/02/2022",
    },
    {
      SNo: 30,
      FullName: "Dr. Rupak Kumar Jha",
      Degree: "MS",
      Speciality: "OPHTHALMOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Nepal Netra Jyoti Sangh.",
      FNDRegistrationNo: "014-99-006498-21",
      RegistrationValidity: "24/02/2022",
    },
    {
      SNo: 31,
      FullName: "Dr. Bhadra Priya",
      Degree: "DNB",
      Speciality: "OPHTHALMOLOGY",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "Nepal Netra Jyoti Sangh.",
      FNDRegistrationNo: "014-99-006499-21",
      RegistrationValidity: "24/02/2022",
    },
    {
      SNo: 32,
      FullName: "Dr. Jayshree Mandal",
      Degree: "DNB",
      Speciality: "OPHTHALMOLOGY",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "Nepal Netra Jyoti Sangh.",
      FNDRegistrationNo: "014-99-006500-21",
      RegistrationValidity: "24/02/2022",
    },
    {
      SNo: 33,
      FullName: "Dr. K.V.S.Hari Kumar",
      Degree: "MD",
      Speciality: "GENERAL MEDICINE",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006476-21",
      RegistrationValidity: "28/02/2022",
    },
    {
      SNo: 34,
      FullName: "Dr. Sheshgiri Choudapurkar",
      Degree: "MS",
      Speciality: "ANATOMY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006478-21",
      RegistrationValidity: "28/02/2022",
    },
    {
      SNo: 35,
      FullName: "Dr. Bhagirathi Gupta",
      Degree: "MD",
      Speciality: "OBST & GYNAE",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "Universal College of Medical Science",
      FNDRegistrationNo: "023-99-006420-20",
      RegistrationValidity: "28/02/2022",
    },
    {
      SNo: 36,
      FullName: "Dr.Bishnu Deo Thakur",
      Degree: "MD",
      Speciality: "GENERAL MEDICINE",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-006479-21",
      RegistrationValidity: "28/02/2022",
    },
    {
      SNo: 37,
      FullName: "Dr.Achal Narain Roy",
      Degree: "MD",
      Speciality: "BIOCHEMISTRY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Janaki Medical College",
      FNDRegistrationNo: "006-99-006480-21",
      RegistrationValidity: "28/02/2022",
    },
    {
      SNo: 38,
      FullName: "Dr. Swati Chakravarti",
      Degree: "MD",
      Speciality: "PAEDIATRICS",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-005207-12",
      RegistrationValidity: "03/03/2022",
    },
    {
      SNo: 39,
      FullName: "Dr. Shikha Dogra",
      Degree: "MD",
      Speciality: "SPEDODONTICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006485-21",
      RegistrationValidity: "13/03/2022",
    },
    {
      SNo: 40,
      FullName: "Dr. Deeptanshu Ganguly",
      Degree: "MD",
      Speciality: "PHARMACOLOGY",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006487-21",
      RegistrationValidity: "13/03/2022",
    },
    {
      SNo: 41,
      FullName: "Dr. Karuna Ramteke",
      Degree: "MD",
      Speciality: "PHARMACOLOGY",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "College of Medical Sciences",
      FNDRegistrationNo: "003-99-006488-21",
      RegistrationValidity: "13/03/2022",
    },
    {
      SNo: 42,
      "FullName": "Dr. Christine Cain Groves",
      Degree: "MD",
      Speciality: "Spinal Injury Rehabilitation",
      Nationality: "USA",
      Gender: "Female",
      WorkingPlace: "Spinal Injury Rehabilitayion Centre",
      FNDRegistrationNo: "99-2115",
      RegistrationValidity: "2022-03-20"
    },
    {
      SNo: 43,
      "FullName": "Dr. Johan Rickard Ottosson",
      Degree: "MEDICAL DOCTOR",
      Speciality: "MEDICAL DOCTOR",
      Nationality: "Sweden",
      Gender: "Male",
      WorkingPlace: "United Mission To Nepal Medical and Development Trust",
      FNDRegistrationNo: "91-1820",
      RegistrationValidity: "2023-03-08"
    },
    {
      SNo: 44,
      "FullName": "Dr. Raj Kumar Singh",
      Degree: "MDS",
      Speciality: "PROSTHODONTICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "B. P. Koirala Institute of Health Sciences",
      FNDRegistrationNo: "47-0320",
      RegistrationValidity: "2022-04-20"
    },
    {
      SNo: 45,
      "FullName": "Dr. Wahegaonkar Krishna Dattatrayarao",
      Degree: "MS",
      Speciality: "ORTHOPAEDICS",
      Nationality: "India",
      Gender: "Male",
      WorkingPlace: "Manipal College of Medical Science",
      FNDRegistrationNo: "37-1509",
      RegistrationValidity: "2022-05-09"
    },
    {
      SNo: 46,
      "FullName": "Dr. Jan Johnsen",
      Degree: "MD",
      Speciality: "OBST & GYNAE",
      Nationality: "Denmark",
      Gender: "Male",
      WorkingPlace: "United Mission To Nepal Medical and Development Trust",
      FNDRegistrationNo: "02-1812",
      RegistrationValidity: "2022-05-12"
    },
    {
      SNo: 47,
      "FullName": "Dr. Lars Michael Hubschle",
      Degree: "MD",
      Speciality: "MD",
      Nationality: "USA",
      Gender: "Male",
      WorkingPlace: "United Mission To Nepal Medical and Development Trust",
      FNDRegistrationNo: "22-1820",
      RegistrationValidity: "2023-11-26"
    },
    {
      SNo: 48,
      "FullName": "Dr. Sahana Mohapatra",
      Degree: "MD",
      Speciality: "COMMUNITY MEDICINE",
      Nationality: "India",
      Gender: "Female",
      WorkingPlace: "Birat Medical College",
      FNDRegistrationNo: "26-1817",
      RegistrationValidity: "2022-05-17"
    },
    {
      SNo: 49,
      "FullName": "Dr. Lester Dornon",
      Degree: "MD",
      Speciality: "ORTHOPEDICS",
      Nationality: "USA",
      Gender: "Male",
      WorkingPlace: "United Mission To Nepal Medical and Development Trust",
      FNDRegistrationNo: "01-2025",
      RegistrationValidity: "2025-10-18"
    },
    {
      SNo: 50,
      "FullName": "Dr. Jaeseong Jang",
      Degree: "MS",
      Speciality: "GENERAL SURGERY",
      Nationality: "Korea",
      Gender: "Male",
      WorkingPlace: "The Leprosy Mission International Nepal",
      FNDRegistrationNo: "31-2320",
      RegistrationValidity: "2025-11-29"
    }
  ];

  
//   const dbURI =  "url/test";

// mongoose.connect(dbURI)
//   .then(() => {
//     console.log("Database connected!");
//     // Insert multiple doctors using insertMany
//     Doctor.insertMany(doctors)
//       .then((savedDoctors) => {
//         console.log('Doctors saved successfully:', savedDoctors);
//       })
//       .catch((err) => {
//         console.error('Error saving doctors:', err);
//       });
//   })
//   .catch((err) => {
//     console.error('Error connecting to database:', err);
//   });